import { UserProfile, ResumeVersion } from '../types/resume';

export const SAMPLE_PROFILES: UserProfile[] = [
  {
    id: 'profile_dewan_mukto',
    name: 'Dewan Mukto - Software & Design',
    targetDomain: 'Software Engineering, Web Development & Marketing',
    description: 'Multi-disciplinary portfolio spanning software/web development, UI/UX design, marketing strategy, and developer research.',
    defaultVersionId: 'ver_mukto_tech_v1_0',
    createdAt: '2026-01-15T09:00:00.000Z',
    updatedAt: '2026-03-22T10:00:00.000Z',
  },
  {
    id: 'profile_mukto_creative',
    name: 'Dewan Mukto - Brand & Strategy',
    targetDomain: 'Digital Marketing, Content & Brand Strategy',
    description: 'Tailored for brand growth, copywriting, digital marketing, and team leadership positions.',
    defaultVersionId: 'ver_mukto_brand_v1_0',
    createdAt: '2026-02-01T10:00:00.000Z',
    updatedAt: '2026-03-22T10:30:00.000Z',
  },
];

export const SAMPLE_VERSIONS: ResumeVersion[] = [
  {
    id: 'ver_mukto_tech_v1_0',
    profileId: 'profile_dewan_mukto',
    parentVersionId: null,
    versionTag: 'v1.0',
    title: 'Full-Stack Developer & UI/UX Designer',
    targetRole: 'Software Developer / Web Engineer',
    notes: 'Optimized for software development, modern web architecture, UI/UX design, and ATS keyword extraction.',
    createdAt: '2026-01-15T09:00:00.000Z',
    updatedAt: '2026-03-22T10:00:00.000Z',
    data: {
      personalInfo: {
        fullName: 'Dewan Mukto',
        headline: 'Writer, Designer, Developer, Marketer',
        email: 'dewanmukto@gmail.com',
        phone: '+1 (709) 555-0149',
        location: 'Greater St. John’s Metropolitan Area, NL, Canada',
        website: 'https://dewanmukto.com',
        linkedin: 'https://linkedin.com/in/dewanmukto',
        github: 'https://github.com/dewanmukto',
        summary:
          'Innovative, multi-disciplinary developer and designer with a proven track record of founding web platforms, designing digital brands, and leading cross-functional teams. Specializes in building high-efficiency static websites, modern web and Android applications, user-centered UI/UX architectures, and data-driven marketing campaigns. Passionate about solving complex problems through clean, lean software engineering.',
      },
      workExperiences: [
        {
          id: 'exp_huanmux',
          company: 'HuanMux',
          role: 'Founder, Software/Web Developer, Researcher',
          location: 'St. John’s, NL, Canada',
          startDate: '2023-07',
          endDate: '',
          isCurrent: true,
          highlights: [
            'Architected and deployed high-performance static websites that minimized hosting overhead while maximizing client uptime and throughput.',
            'Engineered clean, accessible UI interfaces backed by human-centered UX design methodologies in Figma.',
            'Prioritized lean development practices to produce fast, maintainable software using minimal code and system resources.',
            'Produced industry-competing graphics and digital brand assets to effectively communicate technical concepts to audience stakeholders.',
            'Conducted market and demographic research to pinpoint high-value user problems and maximize customer retention.',
          ],
          technologies: ['HTML', 'CSS', 'JavaScript', 'Node.js', 'UI/UX Design', 'Figma', 'Web Development'],
        },
        {
          id: 'exp_sherwin',
          company: 'Sherwin-Williams',
          role: 'Sales Associate',
          location: 'Kenmount Road, St. John’s, NL, Canada',
          startDate: '2022-07',
          endDate: '2023-06',
          isCurrent: false,
          highlights: [
            'Thrived in a fast-paced, teamwork-oriented commercial and retail environment serving contractors and home builders.',
            'Demonstrated visual merchandising restoration skills by aligning store floor layout strictly to corporate planograms.',
            'Delivered superior consultative customer service, driving consistent brand commendations and repeat business.',
            'Synchronized and maintained commercial paint tinting machinery, sustaining a 90-100% operational uptime benchmark.',
          ],
          technologies: ['Customer Engagement', 'Retail Operations', 'Machinery Calibration', 'Inventory Management'],
        },
        {
          id: 'exp_marks',
          company: 'Mark’s',
          role: 'Sales Associate',
          location: 'Kelsey Drive, St. John’s, NL, Canada',
          startDate: '2021-10',
          endDate: '2022-02',
          isCurrent: false,
          highlights: [
            'Ensured customer queries were resolved rapidly with an average turnaround time of 30-55 seconds.',
            'Built enduring rapport and earned repeat loyalty across hundreds of weekly regular patrons.',
            'Multitasked in a high-velocity retail environment responsive to rapid seasonal fashion rotations.',
            'Maintained rigorous health and safety standards while scrutinizing store floor activities to prevent inventory shrinkage.',
          ],
          technologies: ['Customer Service', 'POS Systems', 'Problem Solving', 'Inventory Integrity'],
        },
        {
          id: 'exp_ielts',
          company: 'Dewan IELTS',
          role: 'IELTS Trainer & Curriculum Creator',
          location: 'Sylhet, Bangladesh (Remote)',
          startDate: '2021-01',
          endDate: '2022-02',
          isCurrent: false,
          highlights: [
            'Achieved personal IELTS score of 8.5 overall, preparing students to reach cohort averages of 8.0.',
            'Designed structured curriculum materials and taught students strategies for academic and general exam sections.',
            'Conducted 1-to-1 live coaching sessions and webinars focused on targeted grammatical and vocabulary enhancements.',
            'Recorded, edited, and published educational masterclass videos on YouTube and developed an online article publishing portal.',
          ],
          technologies: ['Curriculum Design', 'Public Speaking', 'Video Production', 'Web Publishing'],
        },
        {
          id: 'exp_anime',
          company: 'Mux Anime Studios',
          role: 'Storyboard Director, Animator & Marketing Strategist',
          location: 'Sylhet, Bangladesh (Global Remote)',
          startDate: '2019-11',
          endDate: '2022-02',
          isCurrent: false,
          highlights: [
            'Led a global distributed team of 41 volunteer artists and enthusiasts in producing original serialized anime productions.',
            'Applied agile production management and critical problem-solving to coordinate sequential animation phases.',
            'Recruited, screened, and onboarded creative talent aligned with technical animation and storyboarding standards.',
            'Mentored and upskilled production staff in digital animation tooling and narrative continuity.',
          ],
          technologies: ['Animation', 'Storyboarding', 'Team Leadership', 'Recruiting', 'Digital Marketing'],
        },
        {
          id: 'exp_surgicals',
          company: 'Life Care Surgicals',
          role: 'Sales & Cashier Specialist',
          location: 'Sylhet, Bangladesh',
          startDate: '2018-02',
          endDate: '2021-07',
          isCurrent: false,
          highlights: [
            'Managed cashier and retail sales operations in a busy family medical supply business.',
            'Utilized office productivity suites to generate invoices, official memos, and inventory replenishment requests.',
          ],
          technologies: ['Office Productivity', 'Cashier Management', 'Customer Invoicing'],
        },
        {
          id: 'exp_pathantula',
          company: 'Pathantula Govt Primary School',
          role: 'English Language Teacher',
          location: 'Sylhet, Bangladesh',
          startDate: '2018-04',
          endDate: '2018-11',
          isCurrent: false,
          highlights: [
            'Taught English language and literacy to primary schoolchildren as part of Duke of Edinburgh Award’s Service Section.',
            'Increased student classroom attendance rate from less than 70% to 98% through interactive storytelling and creative pedagogy.',
          ],
          technologies: ['Instructional Teaching', 'Community Leadership', 'Pedagogy'],
        },
      ],
      educations: [
        {
          id: 'edu_mun',
          institution: 'Memorial University of Newfoundland and Labrador',
          degree: 'Bachelor of Science (BSc)',
          fieldOfStudy: 'Computer Science & Sciences',
          startDate: '2020-09',
          endDate: '2023-12',
          location: 'St. John’s, NL, Canada',
          gpa: '',
          honors: [
            'Memorial University Computer Science Society (MUNCSS)',
            'Memorial University Writer’s Wing (MUNWW)',
          ],
        },
        {
          id: 'edu_ananda_ias',
          institution: 'Anandaniketan School',
          degree: 'IAS (International Advanced Subsidiary / A-Levels)',
          fieldOfStudy: 'General Sciences',
          startDate: '2019-01',
          endDate: '2020-12',
          location: 'Sylhet, Bangladesh',
          gpa: '',
          honors: ['Anandaniketan Earth Club (AEC)', 'Anandaniketan Debate Club (ADC)'],
        },
        {
          id: 'edu_ananda_igcse',
          institution: 'Anandaniketan School',
          degree: 'IGCSE (O-Levels)',
          fieldOfStudy: 'Secondary Education',
          startDate: '2006-01',
          endDate: '2019-12',
          location: 'Sylhet, Bangladesh',
          gpa: '',
          honors: ['Anandaniketan Karate Club (AKC)'],
        },
      ],
      skills: [
        { id: 'sk_py', name: 'Python', category: 'Core Languages', level: 'Advanced', yearsOfExperience: 5 },
        { id: 'sk_js', name: 'JavaScript / Node.js', category: 'Core Languages', level: 'Advanced', yearsOfExperience: 5 },
        { id: 'sk_html', name: 'HTML & CSS', category: 'Core Languages', level: 'Expert', yearsOfExperience: 8 },
        { id: 'sk_java', name: 'Java', category: 'Core Languages', level: 'Intermediate', yearsOfExperience: 3 },
        { id: 'sk_c', name: 'C & Fortran', category: 'Core Languages', level: 'Intermediate', yearsOfExperience: 3 },
        { id: 'sk_php', name: 'PHP & MySQL', category: 'Core Languages', level: 'Intermediate', yearsOfExperience: 3 },
        { id: 'sk_kotlin', name: 'Kotlin & Android Studio', category: 'Mobile & Systems', level: 'Advanced', yearsOfExperience: 3 },
        { id: 'sk_corout', name: 'Kotlin Coroutines', category: 'Mobile & Systems', level: 'Intermediate', yearsOfExperience: 2 },
        { id: 'sk_figma', name: 'UI/UX Design (Figma)', category: 'Design & UX', level: 'Expert', yearsOfExperience: 5 },
        { id: 'sk_canva', name: 'Canva & Brand Design', category: 'Design & UX', level: 'Advanced', yearsOfExperience: 5 },
        { id: 'sk_seo', name: 'Search Engine Optimization (SEO)', category: 'Marketing & Analytics', level: 'Advanced', yearsOfExperience: 5 },
        { id: 'sk_analytics', name: 'Google Analytics', category: 'Marketing & Analytics', level: 'Advanced', yearsOfExperience: 4 },
        { id: 'sk_wp', name: 'WordPress & Webflow', category: 'Web & Platforms', level: 'Advanced', yearsOfExperience: 5 },
        { id: 'sk_mongo', name: 'MongoDB', category: 'Data & Databases', level: 'Intermediate', yearsOfExperience: 3 },
        { id: 'sk_git', name: 'Git & Version Control', category: 'Developer Tools', level: 'Advanced', yearsOfExperience: 5 },
        { id: 'sk_lead', name: 'Cross-functional Team Leadership', category: 'Leadership & Strategy', level: 'Advanced', yearsOfExperience: 5 },
      ],
      projects: [
        {
          id: 'proj_huanmux_web',
          title: 'HuanMux Lean Web Infrastructure',
          role: 'Lead Architect',
          organization: 'HuanMux',
          url: 'https://dewanmukto.com',
          startDate: '2023-07',
          endDate: '',
          description: 'High-speed static website deployment framework prioritizing optimal UX, low latency, and zero hosting bloat.',
          highlights: [
            'Reduced page weight by 65% through optimized static asset delivery and native browser primitives.',
            'Designed cohesive UI design system in Figma adopted across all client properties.',
          ],
          technologies: ['HTML', 'CSS', 'JavaScript', 'Figma', 'DNS Management'],
        },
      ],
      certifications: [
        {
          id: 'cert_scns',
          name: 'Security Certified Network Specialist (SCNS)',
          issuer: 'Security Certified Program (SCP)',
          issueDate: '2022-05',
          expiryDate: '',
          credentialId: 'SCNS-CERT-COMPLETION',
          credentialUrl: '',
        },
        {
          id: 'cert_ga',
          name: 'Google Analytics Individual Qualification',
          issuer: 'Google',
          issueDate: '2022-08',
          expiryDate: '',
          credentialId: 'GA-CERT-VERIFIED',
          credentialUrl: '',
        },
        {
          id: 'cert_ielts',
          name: 'IELTS Band 8.5 Overall Score',
          issuer: 'British Council / IDP / Cambridge',
          issueDate: '2021-01',
          expiryDate: '',
          credentialId: 'IELTS-8.5-ACADEMIC',
          credentialUrl: '',
        },
      ],
      customSections: [
        {
          id: 'cust_languages',
          title: 'Languages',
          items: [
            {
              id: 'lang_1',
              heading: 'English & Bengali',
              subheading: 'Native or Bilingual Proficiency',
              date: '',
              description: 'Fluent in technical communication, academic writing, and public speaking.',
              bullets: [],
            },
            {
              id: 'lang_2',
              heading: 'Hindi & Urdu',
              subheading: 'Full Professional / Professional Working',
              date: '',
              description: 'Effective cross-cultural verbal fluency across South Asian professional contexts.',
              bullets: [],
            },
            {
              id: 'lang_3',
              heading: 'French',
              subheading: 'Elementary Working Proficiency',
              date: '',
              description: 'Basic conversational and written comprehension.',
              bullets: [],
            },
          ],
        },
      ],
      sectionOrder: ['summary', 'experience', 'education', 'skills', 'projects', 'certifications', 'custom'],
      formatting: {
        template: 'carbon-classic',
        fontFamily: 'ibm-plex-sans',
        fontSize: 'normal',
        margins: 'standard',
        accentColor: '#0f62fe',
        showDividerLines: true,
        dateFormat: 'Mon YYYY',
      },
    },
  },
  {
    id: 'ver_mukto_brand_v1_0',
    profileId: 'profile_mukto_creative',
    parentVersionId: null,
    versionTag: 'v1.0',
    title: 'Brand Marketing & Content Strategist',
    targetRole: 'Digital Marketer / Brand Strategist',
    notes: 'Focus on copywriting, SEO, brand positioning, audience retention, and team leadership.',
    createdAt: '2026-02-01T10:00:00.000Z',
    updatedAt: '2026-03-22T10:30:00.000Z',
    data: {
      personalInfo: {
        fullName: 'Dewan Mukto',
        headline: 'Writer, Designer, Marketer | Brand & Growth Specialist',
        email: 'dewanmukto@gmail.com',
        phone: '+1 (709) 555-0149',
        location: 'Greater St. John’s Metropolitan Area, NL, Canada',
        website: 'https://dewanmukto.com',
        linkedin: 'https://linkedin.com/in/dewanmukto',
        github: 'https://github.com/dewanmukto',
        summary:
          'Creative marketer, writer, and brand strategist eager to help businesses thrive, solve audience friction, and maximize customer retention. Combines analytical data acumen (Google Analytics, SEO) with creative storytelling, video production, and international team management to scale brand identity and engagement.',
      },
      workExperiences: [
        {
          id: 'exp_brand_huanmux',
          company: 'HuanMux',
          role: 'Founder & Brand Strategist',
          location: 'St. John’s, NL, Canada',
          startDate: '2023-07',
          endDate: '',
          isCurrent: true,
          highlights: [
            'Spearheaded brand identity development, value proposition messaging, and visual styling for emerging client projects.',
            'Conducted deep demographic research to identify target market personas, increasing client engagement.',
            'Authored persuasive copy and digital brand guidelines to ensure consistent omnichannel brand voice.',
          ],
          technologies: ['Brand Marketing', 'Copywriting', 'SEO', 'Product Design', 'Digital Marketing'],
        },
        {
          id: 'exp_brand_anime',
          company: 'Mux Anime Studios',
          role: 'Creative Director & Marketing Strategist',
          location: 'Sylhet, Bangladesh (Global Remote)',
          startDate: '2019-11',
          endDate: '2022-02',
          isCurrent: false,
          highlights: [
            'Directed marketing and talent recruitment for an international 41-person creative studio.',
            'Built community engagement strategies and promotional story campaigns reaching thousands of global fans.',
          ],
          technologies: ['Creative Direction', 'Storytelling', 'Marketing Strategy', 'Community Building'],
        },
      ],
      educations: [
        {
          id: 'edu_brand_mun',
          institution: 'Memorial University of Newfoundland and Labrador',
          degree: 'Bachelor of Science (BSc)',
          fieldOfStudy: 'Science & Computer Science',
          startDate: '2020-09',
          endDate: '2023-12',
          location: 'St. John’s, NL, Canada',
          gpa: '',
          honors: ['Memorial University Writer’s Wing (MUNWW)'],
        },
      ],
      skills: [
        { id: 'sk_bm_1', name: 'Brand Marketing & Positioning', category: 'Marketing', level: 'Expert', yearsOfExperience: 5 },
        { id: 'sk_bm_2', name: 'Search Engine Optimization (SEO)', category: 'Marketing', level: 'Advanced', yearsOfExperience: 5 },
        { id: 'sk_bm_3', name: 'Copywriting & Content Creation', category: 'Content', level: 'Expert', yearsOfExperience: 6 },
        { id: 'sk_bm_4', name: 'Customer Engagement & Retention', category: 'Marketing', level: 'Advanced', yearsOfExperience: 4 },
        { id: 'sk_bm_5', name: 'Google Analytics & Performance Tracking', category: 'Analytics', level: 'Advanced', yearsOfExperience: 4 },
      ],
      projects: [],
      certifications: [
        {
          id: 'cert_bm_ga',
          name: 'Google Analytics Certification',
          issuer: 'Google',
          issueDate: '2022-08',
          expiryDate: '',
          credentialId: 'GA-CERT-VERIFIED',
          credentialUrl: '',
        },
      ],
      customSections: [],
      sectionOrder: ['summary', 'experience', 'skills', 'education', 'certifications'],
      formatting: {
        template: 'carbon-modern',
        fontFamily: 'ibm-plex-sans',
        fontSize: 'normal',
        margins: 'standard',
        accentColor: '#0f62fe',
        showDividerLines: true,
        dateFormat: 'Mon YYYY',
      },
    },
  },
];
